config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root'albums#index'
  get'/albums/myalbum', to:'albums#myalbum'
  resources :albums 
end

app/models/album.rb
class Album < ApplicationRecord
  has_many_attached :images  
  has_one_attached :cover_image
  belongs_to :user
  has_many :taggings , dependent: :destroy 
  has_many :tags, through: :taggings

  scope :unpublished_albums, -> {where(published:false)}
  scope :published_albums  , -> {where(published:true)}
  
  def self.tagged_with(name)
    Tag.find_by!(name: name).albums
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)  
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings 
  has_many :albums , through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :albums 
  after_create :Send_mail
  private
  def Send_mail
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @q = Album.where(published: true) .ransack(params[:q])
    @albums = @q.result(distinct: true)
  end

  def myalbum
    @q = current_user.albums.ransack(params[:q])
    @UnPublishedAlbums  =  current_user.albums.unpublished_albums.ransack(params[:q]).result(distinct: true)
    @PublishedAlbums =  current_user.albums.published_albums.ransack(params[:q]).result(distinct: true)
  end

  def show 
    @album = Album.find(params[:id])
  end

  def new   
    @album = Album.new  
  end

  def create 
    @album = current_user.albums.new(album_params)
    if @album.save 
      redirect_to @album 
      UserMailer.with(user: current_user).welcome_email.deliver_now
    else 
      render :new , status: :unprocessable_entity 
    end
  end

  def edit 
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update (album_params)
      redirect_to @album 
    else 
      render :edit , status: :unprocessable_entity
    end
  end

  def destroy 
    @album = Album.find(params[:id])
    @album.destroy 
    UserMailer.with(user: current_user).destroy_mail.deliver_now
    redirect_to root_path , status: :see_other
  end  

  private 
  def album_params
    params.require(:album).permit(:name,:description,:published,:allow_download, :cover_image, :tag_list, images:[] )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/albums/_footer.html.erb
<footer class="bg-light fixed-bottom text-center text-lg-start">
 <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <%= link_to "www.galleryapp.com  ", root_path, class:"navbar-brand"%>
  </div>
</footer>

app/views/albums/_form.html.erb
<%= form_with model: album do |form| %>
  <div>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  </div>
  <div>
  <%= form.label :description %><br>
  <%= form.text_area :description %>
  </div>
  <div>
  <%= form.label :published %><br>
  <%= form.check_box :published %>
  </div>
  <div>
  <%= form.label :allow_download %><br>
  <%= form.check_box :allow_download %>
  </div>
  <div>
  <%= form.label :choose_multiple_images %><br><br>
  <%= form.file_field :images, multiple:true%><br><br>
  </div>  
  <div>
  <%= form.label :cover_image %><br><br>
  <%= form.file_field :cover_image %><br>
  </div><br>
  <div>
  <%= form.label :Tags %>
  <%= form.text_field :tag_list %>
  </div><br>
  <div>
  <%= form.submit %>
  </div>  
<%end%>

app/views/albums/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light"> 
  <%= link_to "Gallery App ", root_path, class:"navbar-brand fw-bold link-decoration-none "%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar  navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ">
      <% if user_signed_in? %>
        <li class="nav-item p-1  ">
        <%= link_to "New Album ",new_album_path, class:'text-decoration-none text-dark' %>            
        </li>
        <li class="nav-item p-1 ">
        <%= link_to "Home", albums_path,class:'text-decoration-none text-dark'  %>
        </li>
        <li class="nav-item p-1  ">
        <%= link_to "My Albums ", albums_myalbum_path ,class:'text-decoration-none text-dark'%>
        </li>        
        <li class="nav-item  p-1 ">
        <%= link_to "Logout ", destroy_user_session_path  ,  data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"                                   
        } ,class:'text-decoration-none text-dark' %>
      <% else %>
        <li class="nav-item p-1 link-decoration-none  ">
        <%= link_to "Login" , new_user_session_path ,class:'text-decoration-none text-dark  '%>
        </li>
      <%end%>
    </ul>
 </div>
</nav>

app/views/albums/edit.html.erb
<h4>Edit your album </h4>
<%= render "form",album: @album %>

app/views/albums/index.html.erb
<%= render 'header'%>
<div class="container mt-5 text-center">
<%= search_form_for @q do |f| %>
  <%= f.search_field :tags_name_or_name_cont , placeholder:" Search By Name or Tagname "%>
  <%= f.submit %>
  <% end %>
</div>
<div class="container mt-5 "> 
  <div class="row">
    <% @albums.each do |album| %>    
      <div class="col-lg-3 mt-3 ">
        <a href="/albums/<%= album.id %>" class="text-decoration-none text-black" > 
          <div class="card " style="width: 13rem;">
            <%= image_tag (album.cover_image),style:"width:100%; height:150px"%>
            <div class="card-body">
            <h5 class="card-title">
              <%= album.name  %>                        
            </h5>            
            <h5  class="card-title">
            <%= album.tag_list %>
            </h5>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>
<%= render "footer" %>

app/views/albums/myalbum.html.erb
<%= render 'header'%> 
<div class="container text-center mt-5 ">
  <%= search_form_for @q, url: albums_myalbum_path do |f| %>
  <%= f.search_field :tags_name_or_name_cont , placeholder:" Search By Name or Tagname "%>
  <%= f.submit %>
  <% end %>
</div>
  <div class="container mt-5">
  <h1 class="text-center fw-bold">Published Albums</h1>
    <div class="row">
      <% @PublishedAlbums .each do |album| %>
        <div class="col-lg-3 mt-3 ">
          <a href="/albums/<%= album.id %>" class="text-decoration-none text-black"> 
            <div class="card text-decoration-none " style="width: 13rem;">
              <%= image_tag (album.cover_image )%>
              <div class="card-body">
              <h5 class="card-title">
                <%= album.name %>
              </h5>
              <h5  class="card-title">
              <%= album.tag_list %>
              </h5>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
<div class="container mt-5">
  <h1 class="text-center fw-bold">UnPublished Albums</h1>
    <div class="row">
      <% @UnPublishedAlbums .each do |album| %>
        <div class="col-lg-3 mt-3 ">
          <a href="/albums/<%= album.id %>" class="text-decoration-none text-black">
            <div class="card" style="width: 13rem;">
              <%= image_tag (album.cover_image ),style:"width:100%; height:200px"%>
              <div class="card-body">
                <h5 class="card-title">
                  <%= album.name %>
                </h5>
                <h5  class="card-title">
                <%= album.tag_list %>
                </h5>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
</div>

<%= render'footer' %>

app/views/albums/new.html.erb
<%= render'header'%>
  <div class="container mt-3 ">
    <h3 >Create a new album </h3>
    <%= render "form" ,  album: @album   %>
  </div>
<%= render'footer' %>

app/views/albums/show.html.erb
<%= render 'header'%>
<div class="container mt-4 ">
  <div class="row ">
    <% @album.images.each do |image|%>
      <div class="col-lg-3 mt-5">
        <%= image_tag (image),style: "width: 200px; height: 200px; display: block"%>
      </div>
    <%end%>
  </div>
<br>
  <% if user_signed_in? %>
    <%if current_user.id == @album.user_id %> 
    <%= link_to "Edit" , edit_album_path(@album) %><br><br>
    <%= link_to "Destroy", album_path(@album), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    <%end%>
  <%end%>
</div>
<%= render'footer' %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GalleryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>